# Generated by Django 3.0.5 on 2020-04-06 19:31

from django.db import migrations, models
import validation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_mail', models.CharField(max_length=200, validators=[validation.models.validate_geeks_mail])),
            ],
        ),
    ]
