# Generated by Django 3.0.5 on 2020-04-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='Customer_validation',
        ),
    ]
