"""Metaclass"""

"""Metaclass creates classes and Classes creates objects.

Meta class is responsible for genertion of classes so we can write our own custom
meta class to modify the way classes are generated by performing extra actions 
and injection of code.
"""