# Generated by Django 3.0.5 on 2020-04-23 05:34

import Custome_Validation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_mail', models.CharField(max_length=200, validators=[Custome_Validation.models.validate_geeks_mail])),
            ],
        ),
    ]
